imports:
    - "statementDefinition.yml"

parameters:
    dbDriver: "mysql"
    dbHost: ""
    dbUsername: ""
    dbPassword: ""
    dbName: ""

    identifierDelimiter: "`"

    silktide_reposition.tokenDefinitions: %silktide_reposition-sql.sqlStatementDefinition%

services:
    storage:
        class: Silktide\Reposition\Sql\Storage\SqlStorage
        arguments:
            - @dbAdapter
            - @interpreter
            - @silktide_reposition.defaultHydrator
            - @normaliser

    dbAdapter:
        class: Silktide\Reposition\Sql\Storage\PdoAdapter
        arguments:
            - @credentials

    credentials:
        class: Silktide\Reposition\Sql\Storage\DbCredentials
        arguments:
            - %dbDriver%
            - %dbHost%
            - %dbUsername%
            - %dbPassword%
            - %dbName%

    interpreter:
        class: Silktide\Reposition\Sql\QueryInterpreter\SqlQueryInterpreter
        arguments:
            - @silktide_reposition.tokenParser
            - "#queryTypeInterpreter"
            - %identifierDelimiter%

    findInterpreter:
        class: Silktide\Reposition\Sql\QueryInterpreter\Type\FindInterpreter
        tags:
            - "queryTypeInterpreter"

    normaliser:
        class: Silktide\Reposition\Sql\Normaliser\SqlNormaliser

    silktide_reposition.defaultStorage:
        aliasOf: @storage

    silktide_reposition.defaultNormaliser:
        aliasOf: @normaliser